Quote.create(content:"Harry Potter", category: "Harry Potter")
Quote.create(content:"Ron Weasley", category: "Harry Potter")
Quote.create(content:"Hermoine Granger", category: "Harry Potter")
Quote.create(content:"Albus Dumbledore", category: "Harry Potter")
Quote.create(content:"Cho Chang", category: "Harry Potter")
Quote.create(content:"Sirius Black", category: "Harry Potter")
Quote.create(content:"Severus Snape", category: "Harry Potter")
Quote.create(content:"Draco Malfoy", category: "Harry Potter")
Quote.create(content:"Vernon Dursley", category: "Harry Potter")
Quote.create(content:"Rubeus Hagrid", category: "Harry Potter")
Quote.create(content:"Neville Longbottom", category: "Harry Potter")
Quote.create(content:"Lucius Malfoy", category: "Harry Potter")
Quote.create(content:"Voldemort", category: "Harry Potter")
Quote.create(content:"He Who Must Not Be Named", category: "Harry Potter")
Quote.create(content:"Fred Weasley", category: "Harry Potter")
Quote.create(content:"George Weasley", category: "Harry Potter")
Quote.create(content:"Wands", category: "Harry Potter")
Quote.create(content:"Moaning Myrtle", category: "Harry Potter")
Quote.create(content:"Dolores Umbridge", category: "Harry Potter")
Quote.create(content:"Vincente Crabbe", category: "Harry Potter")
Quote.create(content:"Wand", category: "Harry Potter")
Quote.create(content:"Magic", category: "Harry Potter")
Quote.create(content:"Hogwarts", category: "Harry Potter")
Quote.create(content:"Honeydukes", category: "Harry Potter")
Quote.create(content:"Quidditch", category: "Harry Potter")
Quote.create(content:"Godric Gryffindor", category: "Harry Potter")
Quote.create(content:"Helga Hufflepuff", category: "Harry Potter")
Quote.create(content:"Salazar Slytherin", category: "Harry Potter")
Quote.create(content:"Rowena Ravenclaw", category: "Harry Potter")
Quote.create(content:"Oliver Wood", category: "Harry Potter")
Quote.create(content:"Broomstick", category: "Harry Potter")
Quote.create(content:"Elves", category: "Harry Potter")
Quote.create(content:"Beauxbatons", category: "Harry Potter")
Quote.create(content:"Durmstrang", category: "Harry Potter")
Quote.create(content:"Triwizard Tournament", category: "Harry Potter")
Quote.create(content:"Luna Lovegood", category: "Harry Potter")
Quote.create(content:"Order of the Phoenix", category: "Harry Potter")
Quote.create(content:"Deathly Hallows", category: "Harry Potter")
Quote.create(content:"Philosopher's Stone", category: "Harry Potter")
Quote.create(content:"Sorcerer's Stone", category: "Harry Potter")
Quote.create(content:"Chamber of Secrets", category: "Harry Potter")
Quote.create(content:"Prisoner of Azkaban", category: "Harry Potter")
Quote.create(content:"Goblet of Fire", category: "Harry Potter")
Quote.create(content:"Half Blood Prince", category: "Harry Potter")
Quote.create(content:"Horcruxes", category: "Harry Potter")
Quote.create(content:"Elder Wand", category: "Harry Potter")
Quote.create(content:"Invisibility Cloak", category: "Harry Potter")
Quote.create(content:"Lily Potter", category: "Harry Potter")
Quote.create(content:"Mad Eye Moony", category: "Harry Potter")
Quote.create(content:"King's Cross", category: "Harry Potter")
Quote.create(content:"Wizard", category: "Harry Potter")
Quote.create(content:"Witch", category: "Harry Potter")
Quote.create(content:"Rita Skeeter", category: "Harry Potter")
Quote.create(content:"House Cup", category: "Harry Potter")
Quote.create(content:"Butterbeer", category: "Harry Potter")
Quote.create(content:"House Elf", category: "Harry Potter")
Quote.create(content:"Dobby", category: "Harry Potter")
Quote.create(content:"Socks", category: "Harry Potter")
Quote.create(content:"Friendship", category: "Harry Potter")
Quote.create(content:"Love", category: "Harry Potter")
Quote.create(content:"Valor", category: "Harry Potter")
Quote.create(content:"Ministry of Magic", category: "Harry Potter")
Quote.create(content:"Potion", category: "Harry Potter")
Quote.create(content:"Cauldron", category: "Harry Potter")
Quote.create(content:"Muggle", category: "Harry Potter")

# Quote.create(content:"Boy", category: "Marvel")
Quote.create(content:"Iron Man", category: "Marvel")
Quote.create(content:"Captain America", category: "Marvel")
Quote.create(content:"Black Panther", category: "Marvel")
Quote.create(content:"Spider Man", category: "Marvel")
Quote.create(content:"Thor", category: "Marvel")
Quote.create(content:"Hulk", category: "Marvel")
Quote.create(content:"Vision", category: "Marvel")
Quote.create(content:"Quicksilver", category: "Marvel")
Quote.create(content:"Doctor Strange", category: "Marvel")
Quote.create(content:"Loki", category: "Marvel")
Quote.create(content:"Guardians of Galaxy", category: "Marvel")
Quote.create(content:"Peter Quill", category: "Marvel")
Quote.create(content:"Star Lord", category: "Marvel")
Quote.create(content:"Gamora", category: "Marvel")
Quote.create(content:"Drax the Destroyer", category: "Marvel")
Quote.create(content:"Groot", category: "Marvel")
Quote.create(content:"Rocket", category: "Marvel")
Quote.create(content:"Bucky Barnes", category: "Marvel")
Quote.create(content:"Brooklyn", category: "Marvel")
Quote.create(content:"SHIELD", category: "Marvel")
Quote.create(content:"Nick Fury", category: "Marvel")
Quote.create(content:"Steve Rogers", category: "Marvel")
Quote.create(content:"Black Widow", category: "Marvel")
Quote.create(content:"Natasha Romanoff", category: "Marvel")
Quote.create(content:"Falcon", category: "Marvel")
Quote.create(content:"Tony Stark", category: "Marvel")
Quote.create(content:"Bruce Banner", category: "Marvel")
Quote.create(content:"Scott Lang", category: "Marvel")
Quote.create(content:"Peter Parker", category: "Marvel")
Quote.create(content:"T'Challa", category: "Marvel")
Quote.create(content:"Black Panther", category: "Marvel")
Quote.create(content:"Wakanda", category: "Marvel")
Quote.create(content:"Killmonger", category: "Marvel")
Quote.create(content:"Thanos", category: "Marvel")
Quote.create(content:"Soul Gem", category: "Marvel")
Quote.create(content:"Mind Gem", category: "Marvel")
Quote.create(content:"Odin", category: "Marvel")
Quote.create(content:"Space Gem", category: "Marvel")
Quote.create(content:"Reality Gem", category: "Marvel")
Quote.create(content:"Time Gem", category: "Marvel")
Quote.create(content:"Power Gem", category: "Marvel")
Quote.create(content:"Infinity War", category: "Marvel")
Quote.create(content:"Red Skull", category: "Marvel")
Quote.create(content:"Stan Lee", category: "Marvel")
Quote.create(content:"Falcon", category: "Marvel")
Quote.create(content:"Ragnarok", category: "Marvel")
Quote.create(content:"Asgard", category: "Marvel")
Quote.create(content:"Vibranium", category: "Marvel")
Quote.create(content:"Shield", category: "Marvel")
Quote.create(content:"Mantis", category: "Marvel")
Quote.create(content:"Armor", category: "Marvel")
Quote.create(content:"Action", category: "Marvel")
Quote.create(content:"Earth", category: "Marvel")
Quote.create(content:"Super Hero", category: "Marvel")
Quote.create(content:"Villain", category: "Marvel")
